FROM daocloud.io/nginx

RUN mkdir /wwwroot
COPY nginx.prod.conf /etc/nginx/nginx.conf

RUN mkdir -p /etc/nginx/sites-conf
COPY sites/* /etc/nginx/sites-conf/



EXPOSE 1212

CMD ["service", "nginx", "start"]
