FROM daocloud.io/node:6.9

ENV WD /proj

RUN mkdir -p $WD
WORKDIR $WD

EXPOSE 8000

COPY . $WD/
RUN cd $WD/ && pwd && ls
RUN npm install -g webpack
RUN npm install
RUN npm run dist
CMD ["npm", "start"]
